### ISSUE TITLE
Feed rendering

### ISSUE THREAD

**Issue by rohitvarkey** [kbhat95/kbhat95.github.io#1]
<img width="1258" alt="screen shot 2015-11-22 at 10 26 41 pm" src="https://cloud.githubusercontent.com/assets/5669669/11324997/ef67fba4-9167-11e5-8b89-e678f0911176.png">

This is the way the [feed link](https://kbhat95.github.io/feed.xml) currently renders.

**Comment by kbhat95** [comment]
Which browser are you using? It renders fine on Firefox.

![screenshot from 2015-11-22 22 31 02](https://cloud.githubusercontent.com/assets/7105012/11325029/e5d96fae-9168-11e5-810a-85e8f851db2b.png)

Also, this is the standard feed put out by `jekyll-feed`. Am I missing something?

**Comment by rohitvarkey** [comment]
I'm using Chrome. But I'm suspecting this is due to one of my extensions. Peeked at the console to see this. 
```javascript
Uncaught TypeError: Cannot set property 'cssText' of undefined
chrome-extension://gkojfkhlekighikafcpjkiklfbnlmeio/js/jquery.min.js:2 Uncaught TypeError: Cannot set property 'cssText' of undefined
```
It renders fine on Firefox. I'll close this off anyway!
